icons_format = "<span font_family='Font Awesome 6 Free'>{icon}</span> "

[icons]
icons = "awesome6"
[icons.overrides]
time = ""
cpu = ""
# volume_empty = ""
# volume_half = ""
# volume_full = ""
# volume_muted = ""
# net_wireless = ""
# bat_empty = ""
# bat_10 = ""
# bat_20 = ""
# bat_30 = ""
# bat_40 = ""
# bat_50 = ""
# bat_60 = ""
# bat_70 = ""
# bat_80 = ""
# bat_90 = ""
# bat_full = ""
# bat_quarter = ""
# bat_half = ""
# bat_three_quarters = ""
